//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progevt43
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractOfRawMaterialsPrescribedInTheContract
    {
        public int idContractOfRawMaterialsPrescribedInTheContract { get; set; }
        public int idRawMaterialsPrescribedInTheContract_fk_ { get; set; }
        public int idContract_fk_ { get; set; }
        public int quantityOfGoods { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual RawMaterialsPrescribedInTheContract RawMaterialsPrescribedInTheContract { get; set; }
    }
}
