//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progevt43
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.ContractOfRawMaterialsPrescribedInTheContract = new HashSet<ContractOfRawMaterialsPrescribedInTheContract>();
        }
    
        public int idContract_pk_ { get; set; }
        public int idSupplierCompany_fk_ { get; set; }
        public int idRecipientCompany_fk_ { get; set; }
        public string contractNumberAccordingToInternalRegulations { get; set; }
        public System.DateTime dateOfConclusionOfTheContract { get; set; }
        public int idCountriesSupplierCompany_fk_ { get; set; }
        public int idCountriesRecipientCompany_fk_ { get; set; }
    
        public virtual RecipientCompany RecipientCompany { get; set; }
        public virtual SupplierCompany SupplierCompany { get; set; }
        public virtual Сountries Сountries { get; set; }
        public virtual Сountries Сountries1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractOfRawMaterialsPrescribedInTheContract> ContractOfRawMaterialsPrescribedInTheContract { get; set; }
    }
}
