//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progevt43
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExportOfRawMaterialsEntities : DbContext
    {
        private static ExportOfRawMaterialsEntities _context;
        public ExportOfRawMaterialsEntities()
            : base("name=ExportOfRawMaterialsEntities")
        {
        }
        public static ExportOfRawMaterialsEntities GetContext()
        {
            if (_context == null)
            {
                _context = new ExportOfRawMaterialsEntities();
            }

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<ContractOfRawMaterialsPrescribedInTheContract> ContractOfRawMaterialsPrescribedInTheContract { get; set; }
        public virtual DbSet<RawMaterialsPrescribedInTheContract> RawMaterialsPrescribedInTheContract { get; set; }
        public virtual DbSet<RecipientCompany> RecipientCompany { get; set; }
        public virtual DbSet<SupplierCompany> SupplierCompany { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Сountries> Сountries { get; set; }
    }
}
