//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progevt43
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExportOfRawMaterials2Entities : DbContext
    {
        private static ExportOfRawMaterials2Entities _context;
        public ExportOfRawMaterials2Entities()
            : base("name=ExportOfRawMaterials2Entities")
        {
        }
        public static ExportOfRawMaterials2Entities GetContext()
        {
            if (_context == null)
            {
                _context = new ExportOfRawMaterials2Entities();
            }

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<ContractOfRawMaterialsPrescribedInTheContract> ContractOfRawMaterialsPrescribedInTheContract { get; set; }
        public virtual DbSet<RawMaterialsPrescribedInTheContract> RawMaterialsPrescribedInTheContract { get; set; }
        public virtual DbSet<RecipientCompany> RecipientCompany { get; set; }
        public virtual DbSet<SupplierCompany> SupplierCompany { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Сountries> Сountries { get; set; }
    }
}
