//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progevt43
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialsPrescribedInTheContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RawMaterialsPrescribedInTheContract()
        {
            this.ContractOfRawMaterialsPrescribedInTheContract = new HashSet<ContractOfRawMaterialsPrescribedInTheContract>();
        }
    
        public int idRawMaterialsPrescribedInTheContract_pk_ { get; set; }
        public string name { get; set; }
        public decimal priceOneRawMaterialsPrescribedInTheContract { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractOfRawMaterialsPrescribedInTheContract> ContractOfRawMaterialsPrescribedInTheContract { get; set; }
    }
}
